# Generated by Django 5.2 on 2025-05-14 02:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Grade",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "grade_name",
                    models.CharField(
                        max_length=50, unique=True, verbose_name="Class Name"
                    ),
                ),
                (
                    "grade_number",
                    models.CharField(
                        max_length=50, unique=True, verbose_name="Class Number"
                    ),
                ),
            ],
            options={
                "verbose_name": "Grade",
                "verbose_name_plural": "Grade",
                "db_table": "grades",
                "ordering": ["grade_number"],
            },
        ),
    ]
